### ISSUE TITLE
Fix title for SoapyRTLSDR support module

### ISSUE THREAD

**Issue by neilwillgettoit** [cjcliffe/CubicSDR-Manual#3]
- [x] http://cubicsdr.readthedocs.io/en/latest/building-cubicsdr/linux.html#support-modules title for SoapyRTLSDR support module needs to be fixed. 

This is a reference note for myself to go fix that on the next push.

**Comment by cjcliffe** [comment]
Collaborator invite sent; that will let you push to master when needed.

Cheers!

**Comment by neilwillgettoit** [comment]
oh thanks! will pushes to master also hook to cubicsdr.readthedocs.io ?

**Comment by cjcliffe** [comment]
yup it's automatically building with every push to master.

**Comment by neilwillgettoit** [comment]
fixed in #4
